project/chat/urls.py
from django.urls import path
from . import views


app_name = 'mi_chat'

urlpatterns = [
    path('', views.mostrar_chat, name='chat'),
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import redirect
from mi_blog import views
from mi_blog.sitemaps import PostSitemaps
from django.contrib.sitemaps.views import sitemap

# Redirigir la página principal a la página de login
def redirect_to_login(request):
    return redirect('account_login')  # Redirige a la vista de login de Allauth

sitemaps = {
    'posts': PostSitemaps,
}

urlpatterns = [
    path('', views.custom_login, name='home'),
    path('blog/', include('mi_blog.urls', namespace='blog')),
    path('chat/', include('chat.urls', namespace='chat')),
    path('admin/', admin.site.urls),
    path('friendships/', include('friends.urls' , namespace='friends')),
    path('notifications/', include('notifications.urls' , namespace='notfs')),
    path('accounts/', include('allauth.urls')),
    path('sitemaps.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap')
]
# Solo en desarrollo, Django sirve archivos de medios
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/chat/models.py
from django.db import models

# Create your models here.

project/chat/views.py
from django.shortcuts import render

# Create your views here.
def mostrar_chat(request):
    return render(request, 'chat/chat.html')

project/chat/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Mi Blog{% endblock %}</title>
   
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <style>
        @import url("https://fonts.googleapis.com/css?family=Roboto");
        /* Modal */
    .modal {
        display: none;
        position: fixed;
        z-index: 1;
        left: 0;
        top: 0;
        width: 100%;
        height: 100%;
        background-color: rgba(0, 0, 0, 0.5);
        justify-content: center;
        align-items: center;
    }

    .modal-content {
        background-color: #fff;
        border-radius: 10px;
        padding: 20px;
        position: relative;
        max-width: 80%;
        max-height: 80%;
        overflow: hidden;
    }

    .close {
        position: absolute;
        top: 10px;
        right: 10px;
        font-size: 30px;
        color: #aaa;
        cursor: pointer;
    }

    .close:hover {
        color: black;
    }

    /* Imagen en el modal con tamaño controlado */
    #modalImage {
        width: auto;
        max-width: 400px; /* Limitamos a 400px para no ocupar toda la pantalla */
        max-height: 400px; /* También limitamos la altura */
        height: auto;
        margin: auto;
    }
        body {
            min-height: 100vh;
            font-family: "Roboto", sans-serif;
            color: black;
        }

        * {
            margin: 0;
            padding: 0;
        }

        i {
            margin-right: 10px;
        }

        .navbar-logo {
            padding: 15px;
            color: #fff;
        }

        .navbar-mainbg {
            background-color: #5161ce;
            padding: 0px;
        }

        #navbarSupportedContent {
            overflow: hidden;
            position: relative;
        }

        #navbarSupportedContent ul {
            padding: 0px;
            margin: 0px;
        }

        #navbarSupportedContent ul li a i {
            margin-right: 10px;
        }

        #navbarSupportedContent li {
            list-style-type: none;
            float: left;
        }

        #navbarSupportedContent ul li a {
            color: white !important; /* Texto blanco por defecto */
            text-decoration: none;
            font-size: 15px;
            display: block;
            padding: 20px 20px;
            transition-duration: 0.6s;
            transition-timing-function: cubic-bezier(0.68, -0.55, 0.265, 1.55);
            position: relative;
        }

        #navbarSupportedContent ul li a:hover, 
        #navbarSupportedContent ul li a:focus {
            color: black !important; /* Cambia el color a negro al hacer hover */
            background-color: transparent; /* No cambia el fondo */
            transition: color 0.3s ease; /* Efecto suave de transición */
        }

        #navbarSupportedContent > ul > li.active > a {
            color: #5161ce;
            color: black !important; /* Texto blanco por defecto */
            background-color: transparent;
            transition: all 0.7s;
        }


        .hori-selector {
            display: inline-block;
            position: absolute;
            height: 100%;
            top: 0px;
            left: 0px;
            transition-duration: 0.6s;
            transition-timing-function: cubic-bezier(0.68, -0.55, 0.265, 1.55);
            background-color: #fff;
            border-top-left-radius: 15px;
            border-top-right-radius: 15px;
            margin-top: 10px;
        }

        .hori-selector .right,
        .hori-selector .left {
            position: absolute;
            width: 25px;
            height: 25px;
            background-color: #fff;
            bottom: 10px;
        }

        .hori-selector .right {
            right: -25px;
        }

        .hori-selector .left {
            left: -25px;
        }

        .hori-selector .right:before,
        .hori-selector .left:before {
            content: "";
            position: absolute;
            width: 50px;
            height: 50px;
            border-radius: 50%;
            background-color: #5161ce;
        }

        .hori-selector .right:before {
            bottom: 0;
            right: -25px;
        }

        .hori-selector .left:before {
            bottom: 0;
            left: -25px;
        }

        @media (min-width: 992px) {
            .navbar-expand-custom {
                -ms-flex-flow: row nowrap;
                flex-flow: row nowrap;
                -ms-flex-pack: start;
                justify-content: flex-start;
            }

            .navbar-expand-custom .navbar-nav {
                -ms-flex-direction: row;
                flex-direction: row;
            }

            .navbar-expand-custom .navbar-toggler {
                display: none;
            }

            .navbar-expand-custom .navbar-collapse {
                display: -ms-flexbox !important;
                display: flex !important;
                -ms-flex-preferred-size: auto;
                flex-basis: auto;
            }
        }

        @media (max-width: 991px) {
            #navbarSupportedContent ul li a {
                padding: 12px 30px;
            }

            .hori-selector {
                margin-top: 0px;
                margin-left: 10px;
                border-radius: 0;
                border-top-left-radius: 25px;
                border-bottom-left-radius: 25px;
            }

            .hori-selector .left,
            .hori-selector .right {
                right: 10px;
            }

            .hori-selector .left {
                top: -25px;
                left: auto;
            }

            .hori-selector .right {
                bottom: -25px;
            }

            .hori-selector .left:before {
                left: -25px;
                top: -25px;
            }

            .hori-selector .right:before {
                bottom: -25px;
                left: -25px;
            }
            
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-custom navbar-mainbg">
        <a class="navbar-brand navbar-logo" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <i class="fas fa-bars text-white"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                <div class="hori-selector">
                    <div class="left"></div>
                    <div class="right"></div>
                </div>
                <li class="nav-item">
                    <a class="nav-link" href="javascript:void(0);"><i class="fas fa-tachometer-alt"></i>Home</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="javascript:void(0);"><i class="far fa-address-book"></i>Solicitudes</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#"><i class="far fa-clone"></i>Perfil</a>
                </li>
                <li class="nav-item">
                    <a class="nav-item" href="#"><i class="far fa-clone"></i>Publicar</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'mi_chat:chat' %}"><i class="far fa-chart-bar"></i>Chats</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="javascript:void(0);"><i class="far fa-copy"></i>Documents</a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="container mt-5">
        {% block content %}
        {% endblock %}
    </div>

    <!-- <footer class="text-center mt-5 py-3 bg-dark text-white">
        <p>&copy; 2024 Mi Blog | Todos los derechos reservados</p>
    </footer> -->
    

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <script>
        function test() {
            var tabsNewAnim = $("#navbarSupportedContent");
            var activeItemNewAnim = tabsNewAnim.find(".active");
            var activeWidthNewAnimHeight = activeItemNewAnim.innerHeight();
            var activeWidthNewAnimWidth = activeItemNewAnim.innerWidth();
            var itemPosTopNewAnim = activeItemNewAnim.position();
            var itemPosLeftNewAnim = activeItemNewAnim.position();

            $(".hori-selector").css({
                top: itemPosTopNewAnim.top + "px",
                left: itemPosLeftNewAnim.left + "px",
                height: activeWidthNewAnimHeight + "px",
                width: activeWidthNewAnimWidth + "px"
            });

            $("#navbarSupportedContent").on("click", "li", function (e) {
                $("#navbarSupportedContent ul li").removeClass("active");
                $(this).addClass("active");
                var activeWidthNewAnimHeight = $(this).innerHeight();
                var activeWidthNewAnimWidth = $(this).innerWidth();
                var itemPosTopNewAnim = $(this).position();
                var itemPosLeftNewAnim = $(this).position();

                $(".hori-selector").css({
                    top: itemPosTopNewAnim.top + "px",
                    left: itemPosLeftNewAnim.left + "px",
                    height: activeWidthNewAnimHeight + "px",
                    width: activeWidthNewAnimWidth + "px"
                });
            });
        }
        
        $(document).ready(function () {
            setTimeout(function () {
                test();
            });
        });
        $(document).ready(function () {
            $('#navbarSupportedContent ul li a').hover(
                function () {
                    $(this).addClass('hovered');
                },
                function () {
                    $(this).removeClass('hovered');
                }
            );
        });
    </script>
    <!-- <script src="{% static 'js/scripts.js' %}"></script>  -->
</body>
</html>